// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0C6fVAj_3vvpE1mX_jCtxcCp-MYghIWA',
    appId: '1:1055806224034:web:dcec27feef389bb98789fb',
    messagingSenderId: '1055806224034',
    projectId: 'chat-app-54b55',
    authDomain: 'chat-app-54b55.firebaseapp.com',
    storageBucket: 'chat-app-54b55.appspot.com',
    measurementId: 'G-PMQHXV466F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZXgy7R5se6JhIGzy2OyMI9fadZTOc9K0',
    appId: '1:1055806224034:android:1c137ae3ef0532fc8789fb',
    messagingSenderId: '1055806224034',
    projectId: 'chat-app-54b55',
    storageBucket: 'chat-app-54b55.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6V_C-LTqmyfJcYBkfRaJTTAhd2vjZEHU',
    appId: '1:1055806224034:ios:2c2b5515a59dde178789fb',
    messagingSenderId: '1055806224034',
    projectId: 'chat-app-54b55',
    storageBucket: 'chat-app-54b55.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6V_C-LTqmyfJcYBkfRaJTTAhd2vjZEHU',
    appId: '1:1055806224034:ios:2c2b5515a59dde178789fb',
    messagingSenderId: '1055806224034',
    projectId: 'chat-app-54b55',
    storageBucket: 'chat-app-54b55.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0C6fVAj_3vvpE1mX_jCtxcCp-MYghIWA',
    appId: '1:1055806224034:web:a6523befd3bb83df8789fb',
    messagingSenderId: '1055806224034',
    projectId: 'chat-app-54b55',
    authDomain: 'chat-app-54b55.firebaseapp.com',
    storageBucket: 'chat-app-54b55.appspot.com',
    measurementId: 'G-X6Z3Y64JQ2',
  );
}
